-- Migration: 002 - Create Tables
-- Description: Create all TASY baseline tables
-- Generated: 2025-12-19T13:48:09.953385
-- Total Tables: 1044

SET DEFINE OFF;

-- Table: PAIS
CREATE TABLE USUARIO (
    NR_SEQUENCIA NUMBER (10, 0) NOT NULL,
    DT_ATUALIZACAO DATE NOT NULL,
    NM_USUARIO VARCHAR2 (15) NOT NULL,
    DT_ATUALIZACAO_NREC DATE,
    NM_USUARIO_NREC VARCHAR2 (15)
);

ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_PK PRIMARY KEY (NR_SEQUENCIA);

COMMIT;